---
- name: Build Web and DB Server Docker Image
  hosts: localhost
  connection: local
  tasks:
    - name: Build Docker image from Dockerfile
      community.docker.docker_image:
        name: web_db_server
        build:
          path: .
        source: build
        state: present
